FROM nginx:alpine

# Remove the default config that causes issues
RUN rm /etc/nginx/conf.d/default.conf

# Copy our config
COPY deploy/nginx/nginx.conf /etc/nginx/nginx.conf
COPY deploy/nginx/conf.d/server.conf /etc/nginx/conf.d/server.conf

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
